pipeline {
    agent any
    stages {
        stage ("Clean up"){
            steps{
                //Recursively delete the current directory from the workspace 
                //Ref: https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#deletedir-recursively-delete-the-current-directory-from-the-workspace
                deleteDir() 
            } 
        }
        stage("Clone Repo"){
            steps{
                //The following command will clone the given repo and create directory "jenkins_example" under current workspace
                sh "git clone https://github.com/nitinaryal/jenkins_example"
            }
        }
        stage("Build"){
            steps {
                //dir() step will change current working directory to directory specified as param e.g. in this case "jenkins_example"
                dir("jenkins_example"){
                    //Executing maven clean build command
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("jenkins_example"){
                    //Executing maven clean build command
                    sh "mvn test"
                }
            }
        }
    }
}